#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Mar  3 20:14:03 2020

@author: vicentesmacbook
"""

s = 'aeiobcniug1y389u'
vow = 0
for char in s:
    if char in 'aeiou':
        vow += 1
print('Number of vowels:', vow)